
PluggableTextMorph subclass: #PluggableTextEditorMorph
	uses: TEnableOnHaloMenu
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets'!

!PluggableTextEditorMorph commentStamp: 'AlainPlantec 2/22/2011 08:51' prior: 0!
Multi-line text editor with support for accepting on both each change and/or when keyboard focus changes. Also supports custom selection colour and clickable highlights.

to see later 
uses: TEnableOnHaloMenu

DEPRECATED in 1.3

!
