
MultiCharacterScanner subclass: #MultiDisplayScanner
	instanceVariableNames: 'bitBlt lineY runX foregroundColor backgroundColor fillBlt lineHeight paragraph paragraphColor morphicOffset ignoreColorChanges'
	classVariableNames: ''
	poolDictionaries: 'TextConstants'
	category: 'Graphics-Text'!

!MultiDisplayScanner commentStamp: 'LaurentLaffont 6/8/2011 22:21' prior: 0!
I'm a class related to the computation of characters counting for text flow.!
