
Object subclass: #SoundTheme
	instanceVariableNames: 'sounds'
	classVariableNames: 'Current UseThemeSounds'
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Themes'!

!SoundTheme commentStamp: 'AlainPlantec 1/7/2010 22:41' prior: 0!
Groups a set of sounds to use with a UITheme.
Note that, although instances may have their sounds changed the settings will still indicate the class of theme that is current.!
