
DiffChangeMorph subclass: #PSMCPatchMorph
	instanceVariableNames: 'changeTree selectedChangeWrapper'
	classVariableNames: 'UsedByDefault'
	poolDictionaries: ''
	category: 'Polymorph-Tools-Diff'!

!PSMCPatchMorph commentStamp: 'LaurentLaffont 2/23/2011 20:21' prior: 0!
I'm a Monticello tool based on polymorph used to browse diffs.
Activate me with the setting named 'Use Polymorph difference tools'.!
