
Object subclass: #ZnUserAgentSettings
	instanceVariableNames: 'settings'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Zinc-HTTP-Deprecated'!

!ZnUserAgentSettings commentStamp: 'SvenVanCaekenberghe 12/6/2010 13:04' prior: 0!
I manage the settings for a ZnUserAgent instance. 

I can be subclassed to extend capabilities to include loading settings from a configuration store or maintaining persistent storage for a cookie jar.

Part of Zinc HTTP Components.!
