
AbstractTool subclass: #FlatMessageListBrowser
	instanceVariableNames: 'model textArea preference selectedItem forceAlphabeticalOrder title searchedString list bindings'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'RecentSubmissions-UI'!

!FlatMessageListBrowser commentStamp: 'StephaneDucasse 8/2/2011 22:38' prior: 0!
I'm a new UI which display info using a list instead of a tree. Due to that, I'm faster to display lists of senders and implementors.

self example!
