
PluggableListMorph subclass: #PluggableListMorphByItem
	instanceVariableNames: 'itemList'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Morphic-Pluggable Widgets'!

!PluggableListMorphByItem commentStamp: 'LaurentLaffont 2/23/2011 20:17' prior: 0!
Essentially useless in its current form. Probably intended to eventually deal with actual objects in the list rather than indexing/string-forms!
