
PharoTheme subclass: #PharoOrangeTheme
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Themes'!

!PharoOrangeTheme commentStamp: '<historical>' prior: 0!
I am GLMUITheme2, a small customization based on GLMUITheme (Glamorous) by Tudor Girba.

GLMUITheme2 defaultSettings: nil.

GLMUITheme2 beCurrent.

GLMUITheme2 setPreferredWorldBackground.
World backgroundMorph: nil.
!
