
MessageDialogWindow subclass: #LongMessageDialogWindow
	instanceVariableNames: 'entryText'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Windows'!

!LongMessageDialogWindow commentStamp: 'gvc 9/23/2008 11:36' prior: 0!
Dialog window displaying a message with a single OK button. Escape/return will close. Icon is a themed information icon.
Handles long messages through use of a text editor with potential for scrolling.!
