
Object subclass: #PolymorphSystemSettings
	instanceVariableNames: ''
	classVariableNames: 'DesktopColor DesktopGradientDirection DesktopGradientFillColor DesktopGradientOrigin DesktopImageFileName DesktopLogo DesktopLogoFileName ShowDesktopLogo UseDesktopGradientFill'
	poolDictionaries: ''
	category: 'Settings-Polymorph'!

PolymorphSystemSettings class
	instanceVariableNames: 'usePolymorphDiffMorph'!

!PolymorphSystemSettings commentStamp: 'LaurentLaffont 3/15/2011 20:46' prior: 0!
I provide settings for Morphic appearance (theme, fonts, colors, ...) that can be found and changed in the Settings browser.!
