
EncodedCharSet subclass: #Latin1
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Multilingual-Encodings'!

Latin1 class
	instanceVariableNames: 'rightHalfSequence'!

!Latin1 commentStamp: 'yo 10/19/2004 19:53' prior: 0!
This class represents the domestic character encoding called ISO-8859-1, also known as Latin-1 used for Most of the Western European Languages.!
