SystemOrganization addCategory: #'Tests-Browser'!
SystemOrganization addCategory: #'Tests-Bugs'!
SystemOrganization addCategory: #'Tests-Compiler'!
SystemOrganization addCategory: #'Tests-Compression'!
SystemOrganization addCategory: #'Tests-Digital Signatures'!
SystemOrganization addCategory: #'Tests-Exceptions'!
SystemOrganization addCategory: #'Tests-Ffenestri'!
SystemOrganization addCategory: #'Tests-Files'!
SystemOrganization addCategory: #'Tests-Finalization'!
SystemOrganization addCategory: #'Tests-Localization'!
SystemOrganization addCategory: #'Tests-Monticello'!
SystemOrganization addCategory: #'Tests-Multilingual'!
SystemOrganization addCategory: #'Tests-Object Events'!
SystemOrganization addCategory: #'Tests-ObjectsAsMethods'!
SystemOrganization addCategory: #'Tests-PackageInfo'!
SystemOrganization addCategory: #'Tests-Polymorph-Widgets'!
SystemOrganization addCategory: #'Tests-Release'!
SystemOrganization addCategory: #'Tests-ScriptLoader'!
SystemOrganization addCategory: #'Tests-System'!
SystemOrganization addCategory: #'Tests-SystemChangeNotification'!
SystemOrganization addCategory: #'Tests-SystemHistory'!
SystemOrganization addCategory: #'Tests-SystemSupport'!
SystemOrganization addCategory: #'Tests-SystemTests-Support'!
SystemOrganization addCategory: #'Tests-TextEditors'!
SystemOrganization addCategory: #'Tests-Traits'!
SystemOrganization addCategory: #'Tests-Traits-MOP'!
SystemOrganization addCategory: #'Tests-VM'!
