
RGGlobalDefinition subclass: #RGBehaviorDefinition
	instanceVariableNames: 'superclass methods protocols'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Ring-Core-Kernel'!

!RGBehaviorDefinition commentStamp: 'VeronicaUquillas 5/9/2011 14:30' prior: 0!
An RGBehaviorDefinition is an abstract definition for class-alike entities (e.g. classes, traits)

Instance Variables
	methods:		<Collection>
	protocols:		<Collection>
	superclass:		<Object>!
