
ZnFixedClient subclass: #ZnExtendedFixedClient
	instanceVariableNames: 'preProcessHook postProcessHook newConnectionHook'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Zinc-HTTP-Deprecated'!

!ZnExtendedFixedClient commentStamp: 'SvenVanCaekenberghe 10/4/2011 19:02' prior: 0!
I am ZnExtendedFixedClient, a ZnFixedClient with some hooks to extend its behavior.

DEPRECATED: Please use ZnNeoClient

Part of Zinc HTTP Components!
