
MCTool subclass: #MCCodeTool
	instanceVariableNames: 'items'
	classVariableNames: 'ShowAnnotationPane'
	poolDictionaries: ''
	category: 'MonticelloGUI'!

!MCCodeTool commentStamp: 'nk 11/10/2003 22:00' prior: 0!
MCCodeTool is an abstract superclass for those Monticello browsers that display code.
It contains copies of the various CodeHolder methods that perform the various menu operations in the method list.
!
