
SystemAnnouncement subclass: #ClassRecategorized
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'SystemAnnouncements'!

!ClassRecategorized commentStamp: 'cyrilledelaunay 1/18/2011 10:42' prior: 0!
This announcement will be raised when:
- we set a category to a class (see 'Class >>category:')
- we set a category to a Trait (see Trait>>category:)

It corresponds to the RecategorizedEvent!
