
DialogWindow subclass: #TickDialogWindow
	instanceVariableNames: 'itemsList itemsHeaderName listMorph wrapBlockOrSelector resultStorage listModel defaultValue'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Windows'!

!TickDialogWindow commentStamp: '<historical>' prior: 0!
A TickDialogWindow is a dialog window which contains a TickList where user can pick a list of items.


self example!
