
SelectorException subclass: #ShouldBeImplemented
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Kernel-Exceptions'!

!ShouldBeImplemented commentStamp: 'SvenVanCaekenberghe 4/21/2011 12:34' prior: 0!
I am ShouldBeImplemented, an exception signaled when some method should have been implemented but was not.

This is more like a placeholder during development.!
