
Model subclass: #ThemeSettings
	instanceVariableNames: 'windowColor selectionColor autoSelectionColor buttonColor scrollbarColor standardColorsOnly progressBarColor progressBarProgressColor menuColor menuTitleColor preferGradientFill preferRoundCorner autoMenuColor flatMenu fadedBackgroundWindows fastDragging animationSettings alternativeButtonsInScrollBars scrollBarThickness balloonHelpEnabled tabAmongFields balloonHelpDelayTime maxBalloonHelpLineLength desktopImageLayout menuSelectionColor secondarySelectionColor findReplaceSelectionColor selectionBarColor unfocusedSelectionColor menuSelectionTextColor selectionTextColor secondarySelectionTextColor findReplaceSelectionTextColor'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Themes'!

!ThemeSettings commentStamp: 'gvc 5/18/2007 10:23' prior: 0!
Configurable basic settings for themes.!
