
UIManager subclass: #MorphicUIManager
	uses: TEasilyThemed
	instanceVariableNames: 'interactiveParser'
	classVariableNames: 'UIProcess'
	poolDictionaries: ''
	category: 'Polymorph-Widgets-Themes'!

!MorphicUIManager commentStamp: 'StephaneDucasse 6/5/2011 22:19' prior: 0!
The Morphic ui manager. 

I was packaged in toolbuilder and I may change in the future. For the moment, the goal is to unload toolbuilder. !
