
Object subclass: #FreeTypeNameParser
	instanceVariableNames: 'combinedName familyNameIn styleNameIn delimiters tokens extractedSlant extractedSlantValue extractedUpright extractedStretch extractedWeight italicFlag boldFlag extractedWeightValue extractedStretchValue'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'FreeType-FontManager'!

FreeTypeNameParser class
	instanceVariableNames: 'weightNames stretchNames obliqueNames normalNames italicNames'!
