
MorphTreeModel subclass: #TickSelectionList
	instanceVariableNames: 'defaultValue itemsHeaderName itemsList lastSelectionIndex onSelectionChangedBlockOrAssociation'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'Polymorph-Widgets'!

!TickSelectionList commentStamp: '<historical>' prior: 0!
I am a list of items where each item is linked to a checkbox.
I am based on MorphTreeMorph for rendering

self example!
