
ImageMorph subclass: #AlphaImageMorph
	instanceVariableNames: 'alpha cachedForm layout scale enabled autoSize getImageSelector model'
	classVariableNames: 'DefaultImage'
	poolDictionaries: ''
	category: 'Polymorph-Widgets'!

!AlphaImageMorph commentStamp: 'gvc 5/18/2007 13:52' prior: 0!
Displays an image with the specified alpha value (translucency) and optional scale and layout (scaled, top-right etc.).!
