
Model subclass: #FontChooser
	instanceVariableNames: 'title selectedFontIndex fontList fontListStrings target getSelector setSelector pointSize fontStyleList selectedFontStyleIndex weightValue slantValue stretchValue pointSizeList'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'FreeType-UI'!

!FontChooser commentStamp: 'StephaneDucasse 1/1/2010 18:00' prior: 0!
I'm an object holding information to choose a font from a list of fonts.!
