
TextConverter subclass: #ByteTextConverter
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: 'EventSensorConstants'
	category: 'Multilingual-TextConversion'!

ByteTextConverter class
	instanceVariableNames: 'byteToUnicode unicodeToByte'!

!ByteTextConverter commentStamp: 'michael.rueger 1/27/2009 18:00' prior: 0!
A ByteTextConverter is the abstract class for text converters on single byte encodings.!
