
Object subclass: #MenuRegistrationExample
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'MenuRegistration-example'!

!MenuRegistrationExample commentStamp: 'AlainPlantec 2/17/2010 01:10' prior: 0!
I'm here to show you how to use the menu registration. See class side methods and try it with:
----------------
(PragmaMenuBuilder pragmaKeyword: 'worldMenuExample' model: nil) menu popUpInWorld
----------------
!
