
!ThemeIcons class methodsFor: '*Graphics-Resources-Theme-Icons'!
imageIconContents
	"Private - Method generated with the content of the file /home/plantec/dvpt/Pharo/Sprint-10-09/Icons/image.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAACUAAABOCAYAAACnrd+aAAAABHNCSVQFBQUBSsjp7wAAAPlJ
REFUeF7l2qERg0AQRmEkJSApgRKQlICkBEr4JSUgKQFJCZSApARkHJlEJTNM5pLAsccTT/MZ
mON2o1jLGhvLJirRvFrKNirVZKIwUJnGUwsLlWs4pTBRhXqvhY0q1XnpGqhK7aFdC1WrOaRr
oiTt2rVRjepdYqBaVX/FQnUqf4qJ6lV8FRs1KHeKj3o8cFT2MT7qFTUp3YyP2kLNSt7ioz6h
FsXP+Cg+iv/28b/o1lD8UwL/5Mn/m/GJ4v8h829d+Dd5PlH822H+xGEvFH+KxZ+M7oXiT9uD
XZYwh+JvBbmg+JtmLij+9qILKuZvxDqiIt1Wc1lE3QF1bs/gFoCvXgAAAABJRU5ErkJggg=='! !
