
!ThemeIcons class methodsFor: '*Graphics-Resources-Theme-Icons'!
smallSystemBrowserIconContents
	"Private - Method generated with the content of the file smallSystemBrowser.png"
	^ 'iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAABh0
RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYyLjcyclqEXQAAAINJREFUOE+9UgkOwCAIg/8/GsWI
q45qlmUzIVG5SqmKiFXLjppdLlVlcVLj5hNFvUCY/9G4nuAd0EZyR9LyI2bcscvSMS2AKAbS
Vwi2s/3GQUcxzbxyQ5ECw66FdRPxbj66BUxku/4eAdPDUYlPObgJKQqgRDO1bTlAmEyVdEOn
2U/+Aq6qHwNt2ojQAAAAAElFTkSuQmCC'! !
