
Object subclass: #ZnNetworkingUtils
	instanceVariableNames: 'socketStreamClass secureSocketStreamClass'
	classVariableNames: 'Default DefaultSocketStreamTimeout'
	poolDictionaries: ''
	category: 'Zinc-HTTP-Support'!

!ZnNetworkingUtils commentStamp: 'SvenVanCaekenberghe 5/2/2011 22:05' prior: 0!
I am ZnNetworkingUtils holding various utilities related to HTTP networking.

My class side is a general API.

My instance side is a factory.

Part of Zinc HTTP Components.!
