
AbstractFont subclass: #LogicalFont
	instanceVariableNames: 'realFont emphasis familyName fallbackFamilyNames pointSize stretchValue weightValue slantValue derivatives boldDerivative italicDerivative boldItalicDerivative'
	classVariableNames: ''
	poolDictionaries: ''
	category: 'FreeType-FontManager'!

LogicalFont class
	instanceVariableNames: 'all'!

!LogicalFont commentStamp: 'LaurentLaffont 6/8/2011 22:20' prior: 0!
I describe a font.!
